# Tool Options
tool_tier: minecraft:iron
tool_category: minecraft:axe
break_speed: 20
attack_damage: 9
attack_speed: 1.1
can_sweep_attack: false
can_break_blocks_in_creative: true

# Damageable Options
max_durability: 250
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: machines:star_crystal

# Enchantable Options
enchantment_value: 10
supported_enchantments:
  - minecraft:efficiency
  - minecraft:silk_touch
  - minecraft:fortune
  - minecraft:unbreaking
  - minecraft:mending