# Wearable Options
armor: 7

# Damageable Options
max_durability: 350
repair_ingredient: machines:star_crystal

# Enchantable Options
enchantment_value: 10
supported_enchantments:
  - minecraft:protection
  - minecraft:fire_protection
  - minecraft:blast_protection
  - minecraft:projectile_protection
  - minecraft:thorns
  - minecraft:unbreaking
  - minecraft:mending